# Function
## x^2-4x+5

In [2]:
import numpy as np
import scipy as sc
import pandas as pd

In [3]:
Srate = 0.001
x = []
y = []

for i in range(0,4000):
    x.append(i*Srate)
    y.append(x[i]*x[i] - 4*x[i] + 5)

In [4]:
a = []
b = []

for i in range(0,2000):
    a.append(x[i*2])
    b.append(y[i*2])
train = np.transpose(np.array([np.ones(2000), a, np.square(a), b]))
np.shape(train)

(2000, 4)

In [5]:
del a[:]
del b[:]
for i in range(0,1000):
    a.append(x[i*4+1])
    b.append(y[i*4+1])
validate = np.transpose(np.array([np.ones(1000), a, np.square(a), b]))
np.shape(validate)

(1000, 4)

In [6]:
del a[:]
del b[:]
for i in range(0,1000):
    a.append(x[i*4+3])
    b.append(y[i*4+3])
test = np.transpose(np.array([np.ones(1000), a, np.square(a), b]))
np.shape(test)

(1000, 4)

In [13]:
W = np.random.rand(3,1)
print W
np.shape(W)

[[ 0.42472889]
 [ 0.94338068]
 [ 0.4176345 ]]


(3, 1)

## This is the matrix manipulation method

In [30]:
temp = np.linalg.pinv(np.matmul(train[:,[0,1,2]],np.transpose(train[:,[0,1,2]])))
np.shape(temp)

(2000, 2000)

In [31]:
temp = np.matmul(temp, train[:,[0,1,2]])
np.shape(temp)

(2000, 3)

In [34]:
W = np.matmul(np.transpose(temp), train[:,[3]])
W

array([[ 5.],
       [-4.],
       [ 1.]])

## This is Batch Graient Descent

In [19]:
derivative = np.zeros((3,1))
alpha = 0.03 #learning rate
W = np.random.rand(3,1)

for i in xrange(0,5000):
    Cost = 0.5/2000*(np.matmul(np.transpose(np.subtract(np.matmul(train[:,[0,1,2]], W), train[:,[3]])), np.subtract(np.matmul(train[:,[0,1,2]], W), train[:,[3]])))
    derivative = 1.0/2000*(np.matmul(np.transpose(train[:,[0,1,2]]), np.subtract(np.matmul(train[:,[0,1,2]], W), train[:,[3]])))
    W = np.subtract(W, alpha*derivative)

In [9]:
print W

[[ 4.99747579]
 [-3.99699674]
 [ 0.99932366]]


## This is Newton's Method

In [15]:
W = np.random.rand(3,1)

for i in range(100):
    Cost = 0.5/2000*(np.matmul(np.transpose(np.subtract(np.matmul(train[:,[0,1,2]], W), train[:,[3]])), np.subtract(np.matmul(train[:,[0,1,2]], W), train[:,[3]])))
    
    derivative = 1.0/2000*(np.matmul(np.transpose(train[:,[0,1,2]]), np.subtract(np.matmul(train[:,[0,1,2]], W), train[:,[3]])))
    hessian = 1.0/2000*np.matmul(np.transpose(train[:,[0,1,2]]), train[:,[0,1,2]])
    invHessian = np.linalg.pinv(hessian)
    W = np.subtract(W, np.matmul(invHessian, derivative))

[[ 23.29885424]]
[[ 0.00111822]
 [ 0.69875413]
 [ 0.97758872]]
[[  5.51391598e-28]]
[[ 5.]
 [-4.]
 [ 1.]]
[[  9.93471703e-33]]
[[ 5.]
 [-4.]
 [ 1.]]
[[  9.93471703e-33]]
[[ 5.]
 [-4.]
 [ 1.]]
[[  9.93471703e-33]]
[[ 5.]
 [-4.]
 [ 1.]]
[[  9.93471703e-33]]
[[ 5.]
 [-4.]
 [ 1.]]
[[  9.93471703e-33]]
[[ 5.]
 [-4.]
 [ 1.]]
[[  9.93471703e-33]]
[[ 5.]
 [-4.]
 [ 1.]]
[[  9.93471703e-33]]
[[ 5.]
 [-4.]
 [ 1.]]
[[  9.93471703e-33]]
[[ 5.]
 [-4.]
 [ 1.]]
[[  9.93471703e-33]]
[[ 5.]
 [-4.]
 [ 1.]]
[[  9.93471703e-33]]
[[ 5.]
 [-4.]
 [ 1.]]
[[  9.93471703e-33]]
[[ 5.]
 [-4.]
 [ 1.]]
[[  9.93471703e-33]]
[[ 5.]
 [-4.]
 [ 1.]]
[[  9.93471703e-33]]
[[ 5.]
 [-4.]
 [ 1.]]
[[  9.93471703e-33]]
[[ 5.]
 [-4.]
 [ 1.]]
[[  9.93471703e-33]]
[[ 5.]
 [-4.]
 [ 1.]]
[[  9.93471703e-33]]
[[ 5.]
 [-4.]
 [ 1.]]
[[  9.93471703e-33]]
[[ 5.]
 [-4.]
 [ 1.]]
[[  9.93471703e-33]]
[[ 5.]
 [-4.]
 [ 1.]]
[[  9.93471703e-33]]
[[ 5.]
 [-4.]
 [ 1.]]
[[  9.93471703e-33]]
[[ 5.]
 [-4.]
 [ 1.]]
[[  9.93471703e-33]]
[[ 5.]
 [-4.]

In [16]:
print W

[[ 5.]
 [-4.]
 [ 1.]]
